const MAX_ITEM_COUNT = 10;
export const MAX_ACTIVITY_COUNT = MAX_ITEM_COUNT;
export const MAX_UPGRADE_COUNT = MAX_ITEM_COUNT;
export const MAX_PACKAGE_COUNT = MAX_ITEM_COUNT;
export const MAX_USN_COUNT = MAX_ITEM_COUNT;
