import type { Instance } from "@landscape/types";

export const instances: Instance[] = [
  {
    id: 2,
    title: "Lenovo X1 Carbon Gen 12",
    comment: "",
    cloud_init: {},
    hostname: "appserv2",
    is_default_child: null,
    total_memory: 1024,
    total_swap: 1024,
    reboot_required_flag: false,
    update_manager_prompt: "normal",
    clone_id: null,
    secrets_name: null,
    last_exchange_time: null,
    last_ping_time: "2023-11-29T18:28:25Z",
    tags: ["precise", "server", "webfarm"],
    access_group: "server",
    distribution: "12.04",
    cloud_instance_metadata: {},
    vm_info: null,
    container_info: null,
    ubuntu_pro_info: null,
    is_wsl_instance: false,
    children: [],
    parent: null,
    upgrades: {
      regular: 7,
      security: 0,
    },
    distribution_info: {
      code_name: "precise",
      description: "Ubuntu 12.04 LTS",
      distributor: "Canonical",
      release: "12.04",
    },
    employee_id: null,
    archived: false,

    grouped_hardware: {
      cpu: [
        {
          architecture: "64 b'bits'",
          cache: {
            "L1 cache": "16 KiB",
            "L2 cache": "12 MiB",
          },
          clock_speed: "1.33 GHz",
          flags: [
            {
              code: "fpu",
              title: "[mathematical co-processor]",
            },
            {
              code: "fpu_exception",
              title: "[FPU exceptions reporting]",
            },
            {
              code: "wp",
              title: "wp",
            },
            {
              code: "vme",
              title: "[virtual mode extensions]",
            },
            {
              code: "de",
              title: "[debugging extensions]",
            },
            {
              code: "pse",
              title: "[page size extensions]",
            },
            {
              code: "tsc",
              title: "[time stamp counter]",
            },
            {
              code: "msr",
              title: "[model-specific registers]",
            },
            {
              code: "pae",
              title: "[4GB+ memory addressing (Physical Address Extension)]",
            },
            {
              code: "mce",
              title: "[machine check exceptions]",
            },
            {
              code: "cx8",
              title: "[compare and exchange 8-byte]",
            },
            {
              code: "apic",
              title:
                "[on-chip advanced programmable interrupt controller (APIC)]",
            },
            {
              code: "sep",
              title: "[fast system calls]",
            },
            {
              code: "mtrr",
              title: "[memory type range registers]",
            },
            {
              code: "pge",
              title: "[page global enable]",
            },
            {
              code: "mca",
              title: "[machine check architecture]",
            },
            {
              code: "cmov",
              title: "[conditional move instruction]",
            },
            {
              code: "pat",
              title: "[page attribute table]",
            },
            {
              code: "pse36",
              title: "[36-bit page size extensions]",
            },
            {
              code: "clflush",
              title: "clflush",
            },
            {
              code: "dts",
              title: "[debug trace and EMON store MSRs]",
            },
            {
              code: "acpi",
              title: "[thermal control (ACPI)]",
            },
            {
              code: "mmx",
              title: "[multimedia extensions (MMX)]",
            },
            {
              code: "fxsr",
              title: "[fast floating point save/restore]",
            },
            {
              code: "sse",
              title: "[streaming SIMD extensions (SSE)]",
            },
            {
              code: "sse2",
              title: "[streaming SIMD extensions (SSE2)]",
            },
            {
              code: "ss",
              title: "[self-snoop]",
            },
            {
              code: "ht",
              title: "[HyperThreading]",
            },
            {
              code: "tm",
              title: "[thermal interrupt and status]",
            },
            {
              code: "pbe",
              title: "[pending break event]",
            },
            {
              code: "syscall",
              title: "[fast system calls]",
            },
            {
              code: "nx",
              title: "[no-execute bit (NX)]",
            },
            {
              code: "x86-64",
              title: "[64bits extensions (x86-64)]",
            },
            {
              code: "constant_tsc",
              title: "constant_tsc",
            },
            {
              code: "arch_perfmon",
              title: "arch_perfmon",
            },
            {
              code: "pebs",
              title: "pebs",
            },
            {
              code: "bts",
              title: "bts",
            },
            {
              code: "rep_good",
              title: "rep_good",
            },
            {
              code: "aperfmperf",
              title: "aperfmperf",
            },
            {
              code: "pni",
              title: "pni",
            },
            {
              code: "dtes64",
              title: "dtes64",
            },
            {
              code: "monitor",
              title: "monitor",
            },
            {
              code: "ds_cpl",
              title: "ds_cpl",
            },
            {
              code: "vmx",
              title: "vmx",
            },
            {
              code: "est",
              title: "est",
            },
            {
              code: "tm2",
              title: "tm2",
            },
            {
              code: "ssse3",
              title: "ssse3",
            },
            {
              code: "cx16",
              title: "cx16",
            },
            {
              code: "xtpr",
              title: "xtpr",
            },
            {
              code: "pdcm",
              title: "pdcm",
            },
            {
              code: "dca",
              title: "dca",
            },
            {
              code: "sse4_1",
              title: "sse4_1",
            },
            {
              code: "lahf_lm",
              title: "lahf_lm",
            },
            {
              code: "tpr_shadow",
              title: "tpr_shadow",
            },
            {
              code: "vnmi",
              title: "vnmi",
            },
            {
              code: "flexpriority",
              title: "flexpriority",
            },
            {
              code: "fpu",
              title: "[mathematical co-processor]",
            },
            {
              code: "fpu_exception",
              title: "[FPU exceptions reporting]",
            },
            {
              code: "wp",
              title: "wp",
            },
            {
              code: "vme",
              title: "[virtual mode extensions]",
            },
            {
              code: "de",
              title: "[debugging extensions]",
            },
            {
              code: "pse",
              title: "[page size extensions]",
            },
            {
              code: "tsc",
              title: "[time stamp counter]",
            },
            {
              code: "msr",
              title: "[model-specific registers]",
            },
            {
              code: "pae",
              title: "[4GB+ memory addressing (Physical Address Extension)]",
            },
            {
              code: "mce",
              title: "[machine check exceptions]",
            },
            {
              code: "cx8",
              title: "[compare and exchange 8-byte]",
            },
            {
              code: "apic",
              title:
                "[on-chip advanced programmable interrupt controller (APIC)]",
            },
            {
              code: "sep",
              title: "[fast system calls]",
            },
            {
              code: "mtrr",
              title: "[memory type range registers]",
            },
            {
              code: "pge",
              title: "[page global enable]",
            },
            {
              code: "mca",
              title: "[machine check architecture]",
            },
            {
              code: "cmov",
              title: "[conditional move instruction]",
            },
            {
              code: "pat",
              title: "[page attribute table]",
            },
            {
              code: "pse36",
              title: "[36-bit page size extensions]",
            },
            {
              code: "clflush",
              title: "clflush",
            },
            {
              code: "dts",
              title: "[debug trace and EMON store MSRs]",
            },
            {
              code: "acpi",
              title: "[thermal control (ACPI)]",
            },
            {
              code: "mmx",
              title: "[multimedia extensions (MMX)]",
            },
            {
              code: "fxsr",
              title: "[fast floating point save/restore]",
            },
            {
              code: "sse",
              title: "[streaming SIMD extensions (SSE)]",
            },
            {
              code: "sse2",
              title: "[streaming SIMD extensions (SSE2)]",
            },
            {
              code: "ss",
              title: "[self-snoop]",
            },
            {
              code: "ht",
              title: "[HyperThreading]",
            },
            {
              code: "tm",
              title: "[thermal interrupt and status]",
            },
            {
              code: "pbe",
              title: "[pending break event]",
            },
            {
              code: "syscall",
              title: "[fast system calls]",
            },
            {
              code: "nx",
              title: "[no-execute bit (NX)]",
            },
            {
              code: "x86-64",
              title: "[64bits extensions (x86-64)]",
            },
            {
              code: "constant_tsc",
              title: "constant_tsc",
            },
            {
              code: "arch_perfmon",
              title: "arch_perfmon",
            },
            {
              code: "pebs",
              title: "pebs",
            },
            {
              code: "bts",
              title: "bts",
            },
            {
              code: "rep_good",
              title: "rep_good",
            },
            {
              code: "aperfmperf",
              title: "aperfmperf",
            },
            {
              code: "pni",
              title: "pni",
            },
            {
              code: "dtes64",
              title: "dtes64",
            },
            {
              code: "monitor",
              title: "monitor",
            },
            {
              code: "ds_cpl",
              title: "ds_cpl",
            },
            {
              code: "vmx",
              title: "vmx",
            },
            {
              code: "est",
              title: "est",
            },
            {
              code: "tm2",
              title: "tm2",
            },
            {
              code: "ssse3",
              title: "ssse3",
            },
            {
              code: "cx16",
              title: "cx16",
            },
            {
              code: "xtpr",
              title: "xtpr",
            },
            {
              code: "pdcm",
              title: "pdcm",
            },
            {
              code: "dca",
              title: "dca",
            },
            {
              code: "sse4_1",
              title: "sse4_1",
            },
            {
              code: "lahf_lm",
              title: "lahf_lm",
            },
            {
              code: "tpr_shadow",
              title: "tpr_shadow",
            },
            {
              code: "vnmi",
              title: "vnmi",
            },
            {
              code: "flexpriority",
              title: "flexpriority",
            },
          ],
          model: "Intel(R) Xeon(R) CPU           E5430  @ 2.66GHz",
          vendor: "Intel Corp.",
        },
        {
          architecture: "64 b'bits'",
          cache: {
            "L1 cache": "16 KiB",
            "L2 cache": "12 MiB",
          },
          clock_speed: "1.33 GHz",
          flags: [
            {
              code: "fpu",
              title: "[mathematical co-processor]",
            },
            {
              code: "fpu_exception",
              title: "[FPU exceptions reporting]",
            },
            {
              code: "wp",
              title: "wp",
            },
            {
              code: "vme",
              title: "[virtual mode extensions]",
            },
            {
              code: "de",
              title: "[debugging extensions]",
            },
            {
              code: "pse",
              title: "[page size extensions]",
            },
            {
              code: "tsc",
              title: "[time stamp counter]",
            },
            {
              code: "msr",
              title: "[model-specific registers]",
            },
            {
              code: "pae",
              title: "[4GB+ memory addressing (Physical Address Extension)]",
            },
            {
              code: "mce",
              title: "[machine check exceptions]",
            },
            {
              code: "cx8",
              title: "[compare and exchange 8-byte]",
            },
            {
              code: "apic",
              title:
                "[on-chip advanced programmable interrupt controller (APIC)]",
            },
            {
              code: "sep",
              title: "[fast system calls]",
            },
            {
              code: "mtrr",
              title: "[memory type range registers]",
            },
            {
              code: "pge",
              title: "[page global enable]",
            },
            {
              code: "mca",
              title: "[machine check architecture]",
            },
            {
              code: "cmov",
              title: "[conditional move instruction]",
            },
            {
              code: "pat",
              title: "[page attribute table]",
            },
            {
              code: "pse36",
              title: "[36-bit page size extensions]",
            },
            {
              code: "clflush",
              title: "clflush",
            },
            {
              code: "dts",
              title: "[debug trace and EMON store MSRs]",
            },
            {
              code: "acpi",
              title: "[thermal control (ACPI)]",
            },
            {
              code: "mmx",
              title: "[multimedia extensions (MMX)]",
            },
            {
              code: "fxsr",
              title: "[fast floating point save/restore]",
            },
            {
              code: "sse",
              title: "[streaming SIMD extensions (SSE)]",
            },
            {
              code: "sse2",
              title: "[streaming SIMD extensions (SSE2)]",
            },
            {
              code: "ss",
              title: "[self-snoop]",
            },
            {
              code: "ht",
              title: "[HyperThreading]",
            },
            {
              code: "tm",
              title: "[thermal interrupt and status]",
            },
            {
              code: "pbe",
              title: "[pending break event]",
            },
            {
              code: "syscall",
              title: "[fast system calls]",
            },
            {
              code: "nx",
              title: "[no-execute bit (NX)]",
            },
            {
              code: "x86-64",
              title: "[64bits extensions (x86-64)]",
            },
            {
              code: "constant_tsc",
              title: "constant_tsc",
            },
            {
              code: "arch_perfmon",
              title: "arch_perfmon",
            },
            {
              code: "pebs",
              title: "pebs",
            },
            {
              code: "bts",
              title: "bts",
            },
            {
              code: "rep_good",
              title: "rep_good",
            },
            {
              code: "aperfmperf",
              title: "aperfmperf",
            },
            {
              code: "pni",
              title: "pni",
            },
            {
              code: "dtes64",
              title: "dtes64",
            },
            {
              code: "monitor",
              title: "monitor",
            },
            {
              code: "ds_cpl",
              title: "ds_cpl",
            },
            {
              code: "vmx",
              title: "vmx",
            },
            {
              code: "est",
              title: "est",
            },
            {
              code: "tm2",
              title: "tm2",
            },
            {
              code: "ssse3",
              title: "ssse3",
            },
            {
              code: "cx16",
              title: "cx16",
            },
            {
              code: "xtpr",
              title: "xtpr",
            },
            {
              code: "pdcm",
              title: "pdcm",
            },
            {
              code: "dca",
              title: "dca",
            },
            {
              code: "sse4_1",
              title: "sse4_1",
            },
            {
              code: "lahf_lm",
              title: "lahf_lm",
            },
            {
              code: "tpr_shadow",
              title: "tpr_shadow",
            },
            {
              code: "vnmi",
              title: "vnmi",
            },
            {
              code: "flexpriority",
              title: "flexpriority",
            },
            {
              code: "fpu",
              title: "[mathematical co-processor]",
            },
            {
              code: "fpu_exception",
              title: "[FPU exceptions reporting]",
            },
            {
              code: "wp",
              title: "wp",
            },
            {
              code: "vme",
              title: "[virtual mode extensions]",
            },
            {
              code: "de",
              title: "[debugging extensions]",
            },
            {
              code: "pse",
              title: "[page size extensions]",
            },
            {
              code: "tsc",
              title: "[time stamp counter]",
            },
            {
              code: "msr",
              title: "[model-specific registers]",
            },
            {
              code: "pae",
              title: "[4GB+ memory addressing (Physical Address Extension)]",
            },
            {
              code: "mce",
              title: "[machine check exceptions]",
            },
            {
              code: "cx8",
              title: "[compare and exchange 8-byte]",
            },
            {
              code: "apic",
              title:
                "[on-chip advanced programmable interrupt controller (APIC)]",
            },
            {
              code: "sep",
              title: "[fast system calls]",
            },
            {
              code: "mtrr",
              title: "[memory type range registers]",
            },
            {
              code: "pge",
              title: "[page global enable]",
            },
            {
              code: "mca",
              title: "[machine check architecture]",
            },
            {
              code: "cmov",
              title: "[conditional move instruction]",
            },
            {
              code: "pat",
              title: "[page attribute table]",
            },
            {
              code: "pse36",
              title: "[36-bit page size extensions]",
            },
            {
              code: "clflush",
              title: "clflush",
            },
            {
              code: "dts",
              title: "[debug trace and EMON store MSRs]",
            },
            {
              code: "acpi",
              title: "[thermal control (ACPI)]",
            },
            {
              code: "mmx",
              title: "[multimedia extensions (MMX)]",
            },
            {
              code: "fxsr",
              title: "[fast floating point save/restore]",
            },
            {
              code: "sse",
              title: "[streaming SIMD extensions (SSE)]",
            },
            {
              code: "sse2",
              title: "[streaming SIMD extensions (SSE2)]",
            },
            {
              code: "ss",
              title: "[self-snoop]",
            },
            {
              code: "ht",
              title: "[HyperThreading]",
            },
            {
              code: "tm",
              title: "[thermal interrupt and status]",
            },
            {
              code: "pbe",
              title: "[pending break event]",
            },
            {
              code: "syscall",
              title: "[fast system calls]",
            },
            {
              code: "nx",
              title: "[no-execute bit (NX)]",
            },
            {
              code: "x86-64",
              title: "[64bits extensions (x86-64)]",
            },
            {
              code: "constant_tsc",
              title: "constant_tsc",
            },
            {
              code: "arch_perfmon",
              title: "arch_perfmon",
            },
            {
              code: "pebs",
              title: "pebs",
            },
            {
              code: "bts",
              title: "bts",
            },
            {
              code: "rep_good",
              title: "rep_good",
            },
            {
              code: "aperfmperf",
              title: "aperfmperf",
            },
            {
              code: "pni",
              title: "pni",
            },
            {
              code: "dtes64",
              title: "dtes64",
            },
            {
              code: "monitor",
              title: "monitor",
            },
            {
              code: "ds_cpl",
              title: "ds_cpl",
            },
            {
              code: "vmx",
              title: "vmx",
            },
            {
              code: "est",
              title: "est",
            },
            {
              code: "tm2",
              title: "tm2",
            },
            {
              code: "ssse3",
              title: "ssse3",
            },
            {
              code: "cx16",
              title: "cx16",
            },
            {
              code: "xtpr",
              title: "xtpr",
            },
            {
              code: "pdcm",
              title: "pdcm",
            },
            {
              code: "dca",
              title: "dca",
            },
            {
              code: "sse4_1",
              title: "sse4_1",
            },
            {
              code: "lahf_lm",
              title: "lahf_lm",
            },
            {
              code: "tpr_shadow",
              title: "tpr_shadow",
            },
            {
              code: "vnmi",
              title: "vnmi",
            },
            {
              code: "flexpriority",
              title: "flexpriority",
            },
          ],
          model: "Intel(R) Xeon(R) CPU           E5430  @ 2.66GHz",
          vendor: "Intel Corp.",
        },
      ],
      display: {
        model: "ES1000",
        vendor: "ATI Technologies Inc",
      },
      memory: {
        size: "8 GiB RAM",
      },
      multimedia: {
        model: "Not available",
        vendor: "Not available",
      },
      network: [
        {
          description: "Ethernet interface",
          ip: "10.20.60.130",
          mac: "00:30:48:7d:4d:ee",
          product: "80003ES2LAN Gigabit Ethernet Controller (Copper)",
          vendor: "Intel Corporation",
        },
        {
          description: "Ethernet interface",
          ip: "174.36.184.2",
          mac: "00:30:48:7d:4d:ef",
          product: "80003ES2LAN Gigabit Ethernet Controller (Copper)",
          vendor: "Intel Corporation",
        },
      ],
      pci: [],
      scsi: [],
      storage: [
        {
          description: "ATA Disk",
          partitions: [
            {
              description: "Linux filesystem partition",
              filesystem: "ext2",
              size: "100 MB",
            },
            {
              description: "Extended partition",
              filesystem: "Not available",
              size: "500 GB",
            },
          ],
          product: "WDC WD5002ABYS-0",
          size: "500 GB",
          vendor: "Western Digital",
        },
      ],
      system: {
        bios_capabilities: [
          {
            code: "pci",
            title: "[PCI bus]",
          },
          {
            code: "pnp",
            title: "[Plug-and-Play]",
          },
          {
            code: "upgrade",
            title: "[BIOS EEPROM can be upgraded]",
          },
          {
            code: "shadowing",
            title: "[BIOS shadowing]",
          },
          {
            code: "escd",
            title: "[ESCD]",
          },
          {
            code: "cdboot",
            title: "[Booting from CD-ROM/DVD]",
          },
          {
            code: "bootselect",
            title: "[Selectable boot path]",
          },
          {
            code: "edd",
            title: "[Enhanced Disk Drive extensions]",
          },
          {
            code: "int13floppy2880",
            title: '[3.5" 2.88MB floppy]',
          },
          {
            code: "acpi",
            title: "[ACPI]",
          },
          {
            code: "usb",
            title: "[USB legacy emulation]",
          },
          {
            code: "ls120boot",
            title: "[Booting from LS-120]",
          },
          {
            code: "zipboot",
            title: "[Booting from ATAPI ZIP]",
          },
          {
            code: "biosbootspecification",
            title: "[BIOS boot specification]",
          },
          {
            code: "pci",
            title: "[PCI bus]",
          },
          {
            code: "pnp",
            title: "[Plug-and-Play]",
          },
          {
            code: "upgrade",
            title: "[BIOS EEPROM can be upgraded]",
          },
          {
            code: "shadowing",
            title: "[BIOS shadowing]",
          },
          {
            code: "escd",
            title: "[ESCD]",
          },
          {
            code: "cdboot",
            title: "[Booting from CD-ROM/DVD]",
          },
          {
            code: "bootselect",
            title: "[Selectable boot path]",
          },
          {
            code: "edd",
            title: "[Enhanced Disk Drive extensions]",
          },
          {
            code: "int13floppy2880",
            title: '[3.5" 2.88MB floppy]',
          },
          {
            code: "acpi",
            title: "[ACPI]",
          },
          {
            code: "usb",
            title: "[USB legacy emulation]",
          },
          {
            code: "ls120boot",
            title: "[Booting from LS-120]",
          },
          {
            code: "zipboot",
            title: "[Booting from ATAPI ZIP]",
          },
          {
            code: "biosbootspecification",
            title: "[BIOS boot specification]",
          },
        ],
        bios_date: "Not available",
        bios_vendor: "Phoenix Technologies LTD",
        bios_version: "2.1a (12/20/2008)",
        chassis: "Not available",
        model: "X7DBU",
        serial: "0123456789",
        vendor: "Supermicro",
      },
      usb: [],
    },
  },
  {
    id: 11,
    title: "Dell XPS 13 Plus",
    comment: "",
    cloud_init: {},
    hostname: "bionic-wsl",
    is_default_child: null,
    total_memory: 1024,
    total_swap: 1024,
    reboot_required_flag: false,
    update_manager_prompt: "normal",
    clone_id: null,
    secrets_name: null,
    last_exchange_time: null,
    last_ping_time: "2023-11-29T18:19:25Z",
    tags: ["bionic", "wsl"],
    access_group: "global",
    distribution: "18.04",
    cloud_instance_metadata: {},
    vm_info: null,
    container_info: null,
    ubuntu_pro_info: null,
    is_wsl_instance: true,
    children: [],
    distribution_info: {
      code_name: "bionic",
      description: "Ubuntu 18.04 LTS",
      distributor: "Canonical",
      release: "18.04",
    },
    parent: {
      id: 6,
      title: "Noel's Windows Laptop",
      comment: "",
      cloud_init: {},
      hostname: "noel",
      is_default_child: null,
      total_memory: 1024,
      total_swap: 1024,
      reboot_required_flag: false,
      update_manager_prompt: "normal",
      clone_id: null,
      secrets_name: null,
      last_exchange_time: null,
      last_ping_time: "2023-11-29T18:24:25Z",
      tags: ["laptop", "windows"],
      access_group: "server",
      distribution: "10 / 11",
      cloud_instance_metadata: {},
      vm_info: null,
      container_info: null,
      ubuntu_pro_info: null,
      is_wsl_instance: false,
      distribution_info: {
        description: "Windows 10 / Windows 11",
        distributor: "Microsoft",
        release: "10 / 11",
        code_name: "windows",
      },
      employee_id: null,
      archived: false,
    },
    employee_id: null,
    archived: false,
  },
  {
    id: 7,
    title: "HP EliteBook 840 G10",
    comment: "",
    cloud_init: {},
    hostname: "customwebserver",
    is_default_child: null,
    total_memory: 1024,
    total_swap: 1024,
    reboot_required_flag: false,
    update_manager_prompt: "normal",
    clone_id: null,
    secrets_name: null,
    last_exchange_time: null,
    last_ping_time: "2023-11-29T18:23:25Z",
    tags: ["precise", "server"],
    access_group: "global",
    distribution: "12.04",
    cloud_instance_metadata: {},
    vm_info: null,
    container_info: null,
    ubuntu_pro_info: null,
    is_wsl_instance: false,
    children: [],
    parent: null,
    distribution_info: {
      code_name: "precise",
      description: "Ubuntu 12.04 LTS",
      distributor: "Canonical",
      release: "12.04",
    },
    employee_id: null,
    archived: false,
  },
  {
    id: 3,
    title: "Apple MacBook Pro 16 M3",
    comment: "",
    cloud_init: {},
    hostname: "dbserv1",
    is_default_child: null,
    total_memory: 1024,
    total_swap: 1024,
    reboot_required_flag: false,
    update_manager_prompt: "normal",
    clone_id: null,
    secrets_name: null,
    last_exchange_time: null,
    last_ping_time: "2023-11-29T18:27:25Z",
    tags: ["lucid", "server", "webfarm"],
    access_group: "server",
    distribution: "10.04",
    cloud_instance_metadata: {},
    vm_info: null,
    container_info: null,
    ubuntu_pro_info: null,
    is_wsl_instance: false,
    children: [],
    parent: null,
    upgrades: {
      regular: 7,
      security: 0,
    },
    distribution_info: {
      code_name: "lucid",
      description: "Ubuntu 10.04 LTS",
      distributor: "Canonical",
      release: "10.04",
    },
    employee_id: null,
    archived: false,
  },
  {
    id: 8,
    title: "Framework Laptop 13 AMD",
    comment: "",
    cloud_init: {},
    hostname: "hp1",
    is_default_child: null,
    total_memory: 1024,
    total_swap: 1024,
    reboot_required_flag: false,
    update_manager_prompt: "normal",
    clone_id: null,
    secrets_name: null,
    last_exchange_time: null,
    last_ping_time: "2023-11-29T18:22:25Z",
    tags: ["oneiric", "server"],
    access_group: "global",
    distribution: "11.10",
    cloud_instance_metadata: {},
    vm_info: null,
    container_info: null,
    ubuntu_pro_info: null,
    is_wsl_instance: false,
    children: [],
    parent: null,
    distribution_info: {
      code_name: "oneiric",
      description: "Ubuntu 11.10",
      distributor: "Canonical",
      release: "11.10",
    },
    employee_id: null,
    archived: false,
  },
  {
    id: 5,
    title: "Microsoft Surface Laptop 5",
    comment: "",
    cloud_init: {},
    hostname: "jane",
    is_default_child: null,
    total_memory: 1024,
    total_swap: 1024,
    reboot_required_flag: true,
    update_manager_prompt: "normal",
    clone_id: null,
    secrets_name: null,
    last_exchange_time: null,
    last_ping_time: "2023-11-29T18:25:25Z",
    tags: ["laptop", "lucid"],
    access_group: "global",
    distribution: "10.04",
    cloud_instance_metadata: {},
    vm_info: null,
    container_info: null,
    ubuntu_pro_info: null,
    is_wsl_instance: false,
    children: [],
    parent: null,
    upgrades: {
      regular: 7,
      security: 0,
    },
    distribution_info: {
      code_name: "lucid",
      description: "Ubuntu 10.04 LTS",
      distributor: "Canonical",
      release: "10.04",
    },
    employee_id: null,
    archived: false,
  },
  {
    id: 4,
    title: "Asus Zenbook S 13 OLED",
    comment: "",
    cloud_init: {},
    hostname: "john",
    is_default_child: null,
    total_memory: 1024,
    total_swap: 1024,
    reboot_required_flag: false,
    update_manager_prompt: "normal",
    clone_id: null,
    secrets_name: null,
    last_exchange_time: null,
    last_ping_time: "2023-11-29T18:26:25Z",
    tags: ["laptop", "natty"],
    access_group: "desktop",
    distribution: "11.04",
    cloud_instance_metadata: {},
    vm_info: null,
    container_info: null,
    ubuntu_pro_info: null,
    is_wsl_instance: false,
    children: [],
    parent: null,
    upgrades: {
      regular: 7,
      security: 0,
    },
    distribution_info: {
      code_name: "natty",
      description: "Ubuntu 11.04",
      distributor: "Canonical",
      release: "11.04",
    },
    employee_id: null,
    archived: false,
  },
  {
    id: 9,
    title: "Acer Swift Edge 16",
    comment: "",
    cloud_init: {},
    hostname: "guest1",
    is_default_child: null,
    total_memory: 1024,
    total_swap: 1024,
    reboot_required_flag: false,
    update_manager_prompt: "normal",
    clone_id: null,
    secrets_name: null,
    last_exchange_time: null,
    last_ping_time: "2023-11-29T18:21:25Z",
    tags: ["precise", "server"],
    access_group: "global",
    distribution: "12.04",
    cloud_instance_metadata: {
      "ami-id": "a-1234",
      "instance-id": "m1.tiny",
      "instance-type": "i-5678",
    },
    vm_info: null,
    container_info: null,
    ubuntu_pro_info: null,
    is_wsl_instance: false,
    children: [],
    parent: null,
    distribution_info: {
      code_name: "precise",
      description: "Ubuntu 12.04 LTS",
      distributor: "Canonical",
      release: "12.04",
    },
    employee_id: null,
    archived: false,
  },
  {
    id: 10,
    title: "Razer Blade 14 2024",
    comment: "",
    cloud_init: {},
    hostname: "lxc1",
    is_default_child: null,
    total_memory: null,
    total_swap: null,
    reboot_required_flag: false,
    update_manager_prompt: "normal",
    clone_id: null,
    secrets_name: null,
    last_exchange_time: null,
    last_ping_time: "2023-11-29T18:20:25Z",
    tags: ["precise", "server"],
    access_group: "global",
    distribution: "12.04",
    cloud_instance_metadata: {},
    vm_info: null,
    container_info: "lxc",
    ubuntu_pro_info: null,
    is_wsl_instance: false,
    children: [],
    parent: null,
    distribution_info: {
      code_name: "precise",
      description: "Ubuntu 12.04 LTS",
      distributor: "Canonical",
      release: "12.04",
    },
    employee_id: null,
    archived: true,
  },
  {
    id: 20,
    title: "HP Spectre x360 14",
    comment: "",
    cloud_init: {},
    hostname: "moved-lion.lxd",
    is_default_child: null,
    total_memory: 31872,
    total_swap: 0,
    reboot_required_flag: false,
    update_manager_prompt: "lts",
    clone_id: null,
    secrets_name: null,
    last_exchange_time: "2023-12-13T05:37:58Z",
    last_ping_time: null,
    tags: [],
    access_group: "global",
    distribution: "22.04",
    cloud_instance_metadata: {},
    vm_info: "",
    container_info: "lxc",
    ubuntu_pro_info: {
      result: "success",
      account: {
        created_at: "2019-10-11T13:55:56+00:00",
        external_account_ids: [
          {
            IDs: ["00120000003pnbEAAQ"],
            origin: "Salesforce",
          },
          {
            IDs: ["cus_IPLC3v02vypwyX"],
            origin: "Stripe",
          },
        ],
        id: "aANXOSZO8cuEBUyy-UlFO08rQQvcUF_yTepcjIapchfw",
        name: "Canonical - staff",
      },
      attached: true,

      contract: {
        created_at: "2020-09-29T15:52:51+00:00",
        id: "cAJMR-Wu2xaAS6tCkJ_vAIxedbbcXMnNRIvJ_AdKQcNo",
        name: "Ubuntu Pro (Apps-only) - Virtual",
        products: ["uaa-essential-virtual"],
        tech_support_level: "essential",
      },
      effective: "2020-09-29T00:00:00+00:00",
      expires: "3999-12-31T23:59:59+00:00",
      services: [
        {
          available: "yes",
          blocked_by: [],
          description: "Scalable Android in the cloud",
          description_override: null,
          entitled: "yes",
          name: "anbox-cloud",
          status: "disabled",
          status_details: "Anbox Cloud is not configured",
          warning: null,
        },
        {
          available: "yes",
          blocked_by: [],
          description: "Expanded Security Maintenance for Applications",
          description_override: null,
          entitled: "yes",
          name: "esm-apps",
          status: "enabled",
          status_details: "Ubuntu Pro: ESM Apps is active",
          warning: null,
        },
        {
          available: "yes",
          blocked_by: [],
          description: "Expanded Security Maintenance for Infrastructure",
          description_override: null,
          entitled: "yes",
          name: "esm-infra",
          status: "enabled",
          status_details: "Ubuntu Pro: ESM Infra is active",
          warning: null,
        },
        {
          available: "yes",
          blocked_by: [],
          description:
            "Preview of FIPS crypto packages undergoing certification with NIST",
          description_override: null,
          entitled: "yes",
          name: "fips-preview",
          status: "disabled",
          status_details: "FIPS Preview is not configured",
          warning: null,
        },
        {
          available: "yes",
          blocked_by: [],
          description:
            "FIPS compliant crypto packages with stable security updates",
          description_override: null,
          entitled: "yes",
          name: "fips-updates",
          status: "disabled",
          status_details: "FIPS Updates is not configured",
          warning: null,
        },
        {
          available: "yes",
          blocked_by: [],
          description: "Security compliance and audit tools",
          description_override: null,
          entitled: "yes",
          name: "usg",
          status: "disabled",
          status_details: "Ubuntu Security Guide is not configured",
          warning: null,
        },
      ],
    },
    is_wsl_instance: false,
    children: [],
    parent: null,
    upgrades: {
      regular: 6,
      security: 6,
    },
    alerts: [
      {
        type: "SecurityUpgradesAlert",
        summary: "",
        severity: "info",
      },
    ],
    distribution_info: {
      code_name: "jammy",
      description: "Ubuntu 22.04 LTS",
      distributor: "Canonical",
      release: "22.04",
    },
    employee_id: null,
    archived: false,
  },
  {
    id: 12,
    title: "Lenovo ThinkPad T14s Gen 4",
    comment: "This instance has not reported a distribution yet.",
    cloud_init: {},
    hostname: "new",
    is_default_child: null,
    total_memory: 1024,
    total_swap: 1024,
    reboot_required_flag: false,
    update_manager_prompt: "normal",
    clone_id: null,
    secrets_name: null,
    last_exchange_time: null,
    last_ping_time: "2023-11-29T18:29:25Z",
    tags: [],
    access_group: "server",
    distribution: null,
    cloud_instance_metadata: {},
    vm_info: null,
    container_info: null,
    ubuntu_pro_info: null,
    is_wsl_instance: false,
    children: [],
    parent: null,
    upgrades: {
      regular: 333,
      security: 208,
    },
    distribution_info: null,
    employee_id: null,
    archived: false,
  },
  {
    id: 21,
    title: "LG Gram SuperSlim 15",
    comment: "",
    cloud_init: {},
    hostname: "simple-crow.lxd",
    is_default_child: null,
    total_memory: 31871,
    total_swap: 0,
    reboot_required_flag: false,
    update_manager_prompt: "lts",
    clone_id: null,
    secrets_name: null,
    last_exchange_time: "2024-01-16T22:45:13Z",
    last_ping_time: "2024-01-16T22:57:39Z",
    tags: [],
    access_group: "global",
    distribution: "20.04",
    cloud_instance_metadata: {},
    vm_info: "",
    container_info: "lxc",
    ubuntu_pro_info: {
      result: "success",
      attached: false,
      expires: "n/a",
      services: [
        {
          name: "cc-eal",
          description: "Common Criteria EAL2 Provisioning Packages",
          available: "no",
        },
        {
          name: "esm-apps",
          description: "UA Apps: Extended Security Maintenance",
          available: "yes",
        },
        {
          name: "esm-infra",
          description: "UA Infra: Extended Security Maintenance",
          available: "yes",
        },
        {
          name: "fips",
          description: "NIST-certified FIPS modules",
          available: "yes",
        },
        {
          name: "fips-updates",
          description: "Uncertified security updates to FIPS modules",
          available: "yes",
        },
        {
          name: "livepatch",
          description: "Canonical Livepatch service",
          available: "yes",
        },
      ],
      techSupportLevel: "n/a",
    },
    is_wsl_instance: false,
    children: [],
    parent: null,
    upgrades: {
      regular: 333,
      security: 208,
    },
    distribution_info: {
      code_name: "focal",
      description: "Ubuntu 20.04 LTS",
      distributor: "Canonical",
      release: "20.04",
    },
    employee_id: null,
    archived: false,
  },
];
