import type { ExportFieldGroup, ExportFormValues } from "@/features/exports";
import { INPUT_DATE_FORMAT } from "@/constants";
import date from "@/libs/date";

export const INITIAL_VALUES: ExportFormValues = {
  name: "",
  selectedFieldIds: [],
  retainUntil: date().add(3, "years").format(INPUT_DATE_FORMAT),
};

export const EXPORT_FIELD_GROUPS: readonly ExportFieldGroup[] = [
  {
    title: "Primary Identity",
    key: "primary-identity",
    fields: [
      { id: "id", label: "ID" },
      { id: "hostname", label: "Hostname" },
      { id: "title", label: "Instance name" },
      { id: "os", label: "OS" },
      { id: "status", label: "Status" },
    ],
  },
  {
    title: "Connectivity",
    key: "connectivity",
    fields: [
      { id: "network_ip_address", label: "IP address" },
      { id: "network_interface", label: "Interface" },
      { id: "network_mac_address", label: "MAC address" },
      { id: "network_broadcast_address", label: "Broadcast address" },
      { id: "network_netmask", label: "Netmask" },
      { id: "network_speed", label: "Speed" },
      { id: "network_duplex", label: "Duplex" },
    ],
  },
  {
    title: "Health & Updates",
    key: "health-updates",
    fields: [
      { id: "reboot_required_flag", label: "Reboot required" },
      { id: "alert_count", label: "Alert count" },
      { id: "alerts", label: "Active alerts" },
      { id: "upgrades_security", label: "Security upgrades count" },
      { id: "upgrades_regular", label: "Regular upgrades count" },
      { id: "has_release_upgrades", label: "Release upgrade available" },
      { id: "livepatch_info", label: "Livepatch status" },
      { id: "reboot_packages", label: "Packages needing reboot" },
      { id: "update_manager_prompt", label: "Update manager prompt" },
      { id: "ubuntu_pro_reboot_required_info", label: "Pro reboot info" },
    ],
  },
  {
    title: "Compute & Storage",
    key: "compute-storage",
    fields: [
      { id: "hardware_cpu_cores", label: "CPU cores" },
      { id: "hardware_cpu_model", label: "CPU model" },
      { id: "hardware_cpu_vendor", label: "CPU vendor" },
      { id: "total_memory", label: "Total memory" },
      { id: "hardware_memory_size", label: "Memory size (Hardware)" },
      { id: "total_swap", label: "Total swap" },
      { id: "hardware_disk_size", label: "Total disk size" },
      { id: "computer_type", label: "Computer type" },
      { id: "hardware_system_serial", label: "System serial" },
      { id: "hardware_system_vendor", label: "System vendor" },
      { id: "hardware_system_model", label: "System model" },
      { id: "mount_device", label: "Mount device" },
      { id: "mount_point", label: "Mount point" },
      { id: "mount_filesystem", label: "Filesystem type" },
      { id: "mount_total_space", label: "Total space" },
    ],
  },
  {
    title: "Business Logic",
    key: "business-logic",
    fields: [
      { id: "tags", label: "Tags" },
      { id: "access_group", label: "Access group" },
      { id: "annotations", label: "Annotations" },
      { id: "ubuntu_pro", label: "Ubuntu Pro expiration" },
      {
        id: "ubuntu_pro_subscription_type",
        label: "Ubuntu Pro subscription type",
      },
      { id: "license_type", label: "License type" },
      { id: "account_id", label: "Account ID" },
      { id: "employee_id", label: "Employee ID" },
      { id: "profiles", label: "Associated profiles" },
      { id: "comment", label: "Comment" },
      { id: "archived", label: "Archived" },
    ],
  },
  {
    title: "Advanced Infrastructure & Cloud",
    key: "advanced-infra-cloud",
    fields: [
      { id: "cloud_instance_metadata", label: "Cloud instance metadata" },
      { id: "availability_zone", label: "Availability zone" },
      { id: "vm_info", label: "VM type" },
      { id: "container_info", label: "Container type" },
      { id: "wsl", label: "WSL instance" },
      { id: "wsl_profiles", label: "WSL profiles" },
      { id: "juju_machine_id", label: "Juju machine ID" },
      { id: "juju_model_uuid", label: "Juju model UUID" },
      { id: "create_instance_supported", label: "Instance creation supported" },
    ],
  },
  {
    title: "System IDs & Agent Logs",
    key: "system-ids-logs",
    fields: [
      { id: "hostagent_uid", label: "Host agent UID" },
      { id: "machine_id", label: "Machine ID" },
      { id: "secure_id", label: "Secure ID" },
      { id: "insecure_id", label: "Insecure ID" },
      { id: "clone_id", label: "Clone ID" },
      { id: "current_api", label: "Client API version" },
      { id: "current_version", label: "Client version" },
      { id: "last_ping_time", label: "Last ping" },
      { id: "registered_at", label: "Registered at" },
      { id: "last_exchange_time", label: "Last exchange time" },
      { id: "last_exchange_duration", label: "Last exchange duration" },
      { id: "last_exchange_size", label: "Last exchange size" },
      { id: "consecutive_errors", label: "Consecutive errors" },
      { id: "is_inconsistent", label: "Inconsistent" },
    ],
  },
  {
    title: "Instance Hierarchy",
    key: "instance-hierarchy",
    fields: [
      { id: "parent", label: "Parent instance" },
      { id: "children", label: "Child instances" },
      { id: "num_child", label: "Child instance count" },
      { id: "default_child", label: "Default child" },
      { id: "is_default_child", label: "Is default child" },
    ],
  },
];
