export const AUTOINSTALL_FILE_LANGUAGE = "yaml";
export const AUTOINSTALL_FILE_EXTENSION = `.${AUTOINSTALL_FILE_LANGUAGE}`;
export const AUTOINSTALL_FILE_LANGUAGES = [AUTOINSTALL_FILE_LANGUAGE, "yml"];
