name: Coverage report

on:
  push:
    branches: [dev]

env:
  VITE_API_URL: http://onward.landscape.yuriy.works:9091/api/v2/
  VITE_API_URL_OLD: http://onward.landscape.yuriy.works:9091/api/
  VITE_OLD_DASHBOARD_URL: http://onward.landscape.yuriy.works:8080/
  VITE_APP_TITLE: Landscape
  VITE_ROOT_PATH: /
  VITE_SELF_HOSTED_ENV: true

jobs:
  unit-tests:
    runs-on: [self-hosted, Linux, large]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        env:
          npm_config_cache: /home/ubuntu/landscape-dashboard/.npm
      - name: Check memory usage
        run: free -m
      - name: Run tests
        run: npx --max_old_space_size=4096 vitest run --coverage
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: ./coverage
          retention-days: 1

  tics-report:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Download coverage report artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: ./coverage

      - name: Produce TICS report
        shell: bash
        run: |
          set -x
          export TICSAUTHTOKEN=${{ secrets.TICS_AUTH_TOKEN }}
          curl --silent --show-error "https://canonical.tiobe.com/tiobeweb/TICS/api/public/v1/fapi/installtics/Script?cfg=default&platform=linux&url=https://canonical.tiobe.com/tiobeweb/TICS/" > install_tics.sh
          . ./install_tics.sh
          TICSQServer -project landscape-dashboard -tmpdir /tmp/tics -branchdir .
