name: Vulnerability Scan and SBOM

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 2 * * 1" # Run weekly at 2 AM on Monday
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/security.yaml'

permissions:
  contents: read
  packages: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=sha,prefix=scan-

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Save image to a tar file
        run: docker save ${{ steps.meta.outputs.tags }} -o image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tar
          path: image.tar
          retention-days: 1

  scan-and-report:
    name: Vulnerability Scan
    needs: build-image
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tar

      - name: Install secscan client
        run: |
          sudo snap install canonical-secscan-client
          sudo snap connect canonical-secscan-client:home system:home

      - name: Run security scan
        continue-on-error: true
        id: scan
        run: |
          secscan-client --batch submit \
            --ssdlc-product-name 'landscape-ui' \
            --ssdlc-cycle '25.10' \
            --ssdlc-product-version '1.17.0' \
            --ssdlc-product-channel 'edge' \
            --scanner trivy \
            --type container-image \
            --format oci \
            image.tar \
            --wait-and-print > secscan-results.txt

      - name: Analyze Scan Results
        if: always()
        id: analysis
        run: |
          EXIT_CODE=${{ steps.scan.exit_code }}
          echo "Scan step exited with code: $EXIT_CODE"
          if [ "$EXIT_CODE" == "0" ]; then
            echo "Success: Scan completed and no vulnerabilities were found."
            exit 0
          fi
          if [ "$EXIT_CODE" -ge 100 ] && [ "$EXIT_CODE" -lt 200 ]; then
            echo "::error::Vulnerabilities were detected by the scan."
            exit 1
          fi
          echo "::error::The security scan failed to run properly. Exit code: $EXIT_CODE"
          exit 1

      - name: Create Issue on Failure
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Vulnerability scan found issues or failed to run for Landscape UI." > issue-body.txt
          echo "" >> issue-body.txt
          echo "**Job:** [${{ github.job }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> issue-body.txt
          echo "" >> issue-body.txt
          echo "### Scan Output" >> issue-body.txt
          echo '```' >> issue-body.txt
          if [ -f secscan-results.txt ]; then cat secscan-results.txt; else echo "Scan results file not found."; fi >> issue-body.txt
          echo '```' >> issue-body.txt
          gh issue create --title "Vulnerability Scan Failed for Landscape UI" --body-file issue-body.txt --label "security,bug"

  sbom-generation:
    name: Generate SBOM
    needs: build-image
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tar

      - name: Checkout sbomber tool
        uses: actions/checkout@v4
        with:
          repository: canonical/sbomber
          path: sbomber

      - name: Install Prerequisites
        uses: astral-sh/setup-uv@v1

      - name: Install secscan client
        run: |
          sudo snap install canonical-secscan-client
          sudo snap connect canonical-secscan-client:home system:home

      - name: Create sbomber manifest
        run: |
          cat <<EOF > sbomber/manifest.yaml
          clients:
            sbom:
                department: Web Engineering
                email: yurii.vasyliev@canonical.com
                team: Landscape
          artifacts:
            - name: landscape-ui-container
              type: container
              path: ../image.tar # Relative path from sbomber dir
          EOF

      - name: Run sbomber to generate SBOM
        id: sbomber
        continue-on-error: true
        run: |
          cd sbomber
          chmod +x sbomber
          ./sbomber sequential sbom manifest.yaml

      - name: Check SBOM Generation Status
        if: always()
        run: |
          if [ "${{ steps.sbomber.outcome }}" == "success" ]; then
            echo "SBOM generation completed successfully."
          else
            echo "::error::SBOM generation failed. Check the logs from the 'Run sbomber' step for details."
            exit 1
          fi

      - name: Upload SBOM Reports
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: sbom-reports
          path: sbomber/reports/
          retention-days: 90