name: Full TICS report

on:
  push:
    branches: [main]

jobs:
  tics-report:
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage report artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: ${{ github.workspace }}/coverage

      - uses: actions/checkout@v4
      - name: TICS report
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: landscape-dashboard
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          branchdir: ${{ github.workspace }}
          ticsAuthToken: ${{ secrets.TICS_AUTH_TOKEN }}
          installTics: true
