name: Full TICS report

on: workflow_dispatch

jobs:
  unit-tests:
    runs-on: [self-hosted, Linux, large]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.1
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests with coverage
        run: pnpm exec vitest run --coverage
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vitest-report
          path: ${{ github.workspace }}/reports
          retention-days: 30

  tics-report:
    runs-on: [self-hosted, linux, amd64, tiobe, jammy]
    needs: unit-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.1
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download coverage report artifact
        uses: actions/download-artifact@v4
        with:
          name: vitest-report
          path: ${{ github.workspace }}/reports

      - name: TICS report
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: landscape-ui
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true